### ISSUE TITLE
Enhancement request:select image version as HOMEBRIDGE_VERSION 

### ISSUE THREAD

**Issue by GravityRZ** [marcoraddatz/homebridge-docker#40]
i noticed that you can force specific versions in the .env file
the versions to choose from are either the npm range or the release tag.
however it would be easier to choose the package version

eg : image version 4.1 seems to correspond with 0.4.33 so why can we not choose 4.1 as HOMEBRIDGE_VERSION

otherwise is there a list so we know which image version corresponds with which release tag

**Comment by marcoraddatz** [comment]
The Homebridge version gets updated to its newest version every time I do a Docker build. So theoretically I could change the default version without changing a single line of code, just by triggering the 4.1 branch again. That's why I let the user decide, which version he wants to use.

Also, starting the container is much faster, when no version is selected. In v4.1, Homebridge v0.4.32 is pre-installed. All changes are documented in the [changelog](https://github.com/marcoraddatz/homebridge-docker/blob/master/CHANGELOG.md), but maybe I should add an info to the top of the readme?
