### ISSUE TITLE
Synology docker already set the DS_HOSTNAME variable，but i can't find homebridge on my IOS device

### ISSUE THREAD

**Issue by spanbin** [marcoraddatz/homebridge-docker#55]
<img width="1437" alt="qq20180925-212612 2x" src="https://user-images.githubusercontent.com/17084270/46019088-e1b0dc00-c10d-11e8-81b7-f87ff1fd8b45.png">

I have already add DS_HOSTNAME variable，but my iPhone can't find homebridge

**Comment by deadbone** [comment]
Hi,
What means 32770 et 32771 ? Are they port from the Host ? Because you must configure your conteneur to use the same network as the host 
![capture d ecran 2018-09-25 a 17 11 01](https://user-images.githubusercontent.com/5513369/46023988-232d9100-c0e6-11e8-8e7e-7341797078d5.png)

So in my case, no specific ports are seen
You can see my instance running 👍 
![capture d ecran 2018-09-25 a 17 13 53](https://user-images.githubusercontent.com/5513369/46024185-85869180-c0e6-11e8-8dcb-4f4e018b1ce3.png)

Did you follow the instructions in the wiki ? Perhaps you just miss this step :) 
Hope that will help

**Comment by marcoraddatz** [comment]
Thanks @deadbone for your instant reply!

**Comment by spanbin** [comment]
I try to fix setup like this, but i can't find homeridge on my iPhone.

homebridge
<img width="924" alt="1" src="https://user-images.githubusercontent.com/17084270/46088945-11301900-c1e0-11e8-8e0c-55d5628a9c97.png">

config.json
<img width="696" alt="2" src="https://user-images.githubusercontent.com/17084270/46088967-1db47180-c1e0-11e8-82fe-401f7e016696.png">

homebridge log
<img width="695" alt="3" src="https://user-images.githubusercontent.com/17084270/46088992-273dd980-c1e0-11e8-8e2b-6e6359321bd1.png">

iphone can't find home bridge. IOS11.4.1
![4](https://user-images.githubusercontent.com/17084270/46089144-7b48be00-c1e0-11e8-8a54-db9bb0d3443f.png)

**Comment by deadbone** [comment]
Hi,
I don't use the QR code, I always use the code shown on your screenshot.
Could you send the .env file ?
Did you change the settings or did you make a new instance  ?

Something to try (because your docker's image seems to start correctly) : 
delete your homebridge instance
On your synology : erase the 2 folders accessories and persist in your docker folder
In your config.json : change the port by the default port (51826) and change the PIN (just change some digits ;))
create a new homebridge instance 

then
try appairing which the home app and use the code (not the QR code)
or
try appairing with the EVE app (free) and far better (sorry Apple)

last thing : your iPhone and your synology are on the same network ? 

ps : last thing : I can't read text on your screenshot (I only speak french and a very bad english :))
